### ISSUE TITLE
Configure the bundle in your config

### ISSUE THREAD

**Issue by guillaumecardon** [mhujer/BreadcrumbsBundle#14]
Hello,

In Symfony >=4, there isn't file "app/config/config.yml". 
So we can't add the bundle configuration : `white_october_breadcrumbs: ~`, described in the part 3 of your installation guide.

Need to create a specific "config.yml" file or can we add bundle configuration in other file ?
Thanks for you help

**Comment by guillaumecardon** [comment]
Answer : 
Create a file "white_october_breadcrumbs.yaml" in "/config/packages" and copy-paste your configuration : for example
```
white_october_breadcrumbs:
    separator:          'pouet'
    separatorClass:     'separator'
    listId:             'wo-breadcrumbs'
    listClass:          'breadcrumb'
```

**Comment by mhujer** [comment]
@guillaumecardon thanks for pointing that out! I've updated the README to show the instructions for Symfony Flex application structure.
