### ISSUE TITLE
Expose namespaces

### ISSUE THREAD

**Issue by ro0NL** [mhujer/BreadcrumbsBundle#24]
There's no way to obtain the breadcrumbs per namespace, eg. `Breadcrumbs::getNamespaces()`, as generic purpose extension point.

I'd like to traverse all breadcrumb lists for SEO reasons :)

**Comment by mhujer** [comment]
@ro0NL Hi, have a look at https://github.com/mhujer/BreadcrumbsBundle/pull/25 and please let me know what you think.
