### ISSUE TITLE
PHP 8.1 deprecation warnings

### ISSUE THREAD

**Issue by Knallcharge** [mhujer/BreadcrumbsBundle#32]
After updating to PHP 8.1 the following warnings are issued:

> Deprecated: Return type of APY\BreadcrumbTrailBundle\BreadcrumbTrail\Trail::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in vendor\apy\breadcrumbtrail-bundle\src\BreadcrumbTrail\Trail.php on line 199
> Deprecated: Return type of APY\BreadcrumbTrailBundle\BreadcrumbTrail\Trail::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in vendor\apy\breadcrumbtrail-bundle\src\BreadcrumbTrail\Trail.php on line 191

**Comment by mhujer** [comment]
@Knallcharge are you sure that you are using this bundle? The error message mentions `APY\BreadcrumbTrailBundle\BreadcrumbTrail\Trail::getIterator()`

**Comment by Knallcharge** [comment]
@mhujer 
Sorry, I was looking for an APY-alternative and posted the issue to the wrong repo, sorry for that! :)

**Comment by mhujer** [comment]
@Knallcharge to be honest, I can't imagine using attributes to configure breadcrumbs. Typically I use also some values from entities in the breadcrumbs and they are only available in the controller action itself. Would you please describe the use-case in the separate issue please?

**Comment by Knallcharge** [comment]
sure
